### ISSUE TITLE
日志收集kafka配置开启sasl SCRAM-SHA-512出现启动报错

### ISSUE THREAD

**Issue by feelyy** [flashcatcloud/categraf#1121]
### Relevant config.toml

```toml
[root@szc11071 categraf-v0.3.86-linux-amd64]# cat conf/logs.toml |grep -Ev "^$|^#"
[logs]
api_key = "ef4ahfbwzwwtlwfpbertgq1i6mq0ab1q"
enable = true
send_to = "10.172.32.19:1102"
send_type = "kafka"
topic = "systemlog"
use_compress = false
send_with_tls = false
batch_wait = 5
run_path = "/opt/categraf/run"
open_files_limit = 100
scan_period = 10
frame_size = 9000
chan_size = 1000
pipeline=4
kafka_version="2.4.0"
batch_max_concurrence = 0
batch_max_size=100
batch_max_content_size=1000000
producer_timeout= 10
sasl_enable = true
sasl_user = "admin"
sasl_password = "Uh1eLCr3ogTNMMen"
sasl_mechanism= "SCRAM-SHA-512"
sasl_version=1
sasl_handshake = true
enable_collect_container=false
collect_container_all = true
  ## glog processing rules
  # [[logs.Processing_rules]]
  ## single log configure
  [[logs.items]]
  ## file/journald/tcp/udp
  type = "file"
  ## type=file, path is required; type=journald/tcp/udp, port is required
  path = "/var/log/messages"
  source = "syslog"
  service = "systemlog"
```

### Logs from categraf

```text
[root@szc11071 categraf-v0.3.86-linux-amd64]# ./categraf --debug --test --inputs logs-agent
2024/12/31 15:46:07 main.go:149: I! runner.binarydir: /usr/local/categraf-v0.3.86-linux-amd64
2024/12/31 15:46:07 main.go:150: I! runner.hostname: szc11071
2024/12/31 15:46:07 main.go:151: I! runner.fd_limits: (soft=524288, hard=524288)
2024/12/31 15:46:07 main.go:152: I! runner.vm_limits: (soft=unlimited, hard=unlimited)
2024/12/31 15:46:07 provider_manager.go:60: I! use input provider: [local]
2024/12/31 15:46:07 logs_agent.go:87: I! Starting logs-agent...
2024/12/31 15:46:07 prometheus_agent.go:19: I! prometheus scraping disabled!
2024/12/31 15:46:07 ibex_agent.go:19: I! ibex agent disabled!
2024/12/31 15:46:07 agent.go:38: I! agent starting
2024/12/31 15:46:07 agent.go:46: I! [*agent.MetricsAgent] started
2024/12/31 15:46:07 destination.go:122: D! producer type: sync 256 5
2024/12/31 15:46:07 destination.go:154: D! saram config: &{Admin:{Retry:{Max:5 Backoff:100ms} Timeout:3s} Net:{MaxOpenRequests:5 DialTimeout:30s ReadTimeout:30s WriteTimeout:30s ResolveCanonicalBootstrapServers:false TLS:{Enable:false Config:<nil>} SASL:{Enable:true Mechanism:SCRAM-SHA-512 Version:1 Handshake:true AuthIdentity: User:admin Password:Uh1eLCr3ogTNMMen SCRAMAuthzID: SCRAMClientGeneratorFunc:<nil> TokenProvider:<nil> GSSAPI:{AuthType:0 KeyTabPath: CCachePath: KerberosConfigPath: ServiceName: Username: Password: Realm: DisablePAFXFAST:false}} KeepAlive:0s LocalAddr:<nil> Proxy:{Enable:false Dialer:<nil>}} Metadata:{Retry:{Max:3 Backoff:250ms BackoffFunc:<nil>} RefreshFrequency:10m0s Full:true Timeout:0s AllowAutoTopicCreation:true} Producer:{MaxMessageBytes:1000000 RequiredAcks:1 Timeout:10s Compression:none CompressionLevel:-1000 Partitioner:0xb27340 Idempotent:false Transaction:{ID: Timeout:1m0s Retry:{Max:50 Backoff:100ms BackoffFunc:<nil>}} Return:{Successes:true Errors:true} Flush:{Bytes:0 Messages:0 Frequency:0s MaxMessages:0} Retry:{Max:3 Backoff:100ms BackoffFunc:<nil>} Interceptors:[]} Consumer:{Group:{Session:{Timeout:10s} Heartbeat:{Interval:3s} Rebalance:{Strategy:<nil> GroupStrategies:[0xc000616b10] Timeout:1m0s Retry:{Max:4 Backoff:2s}} Member:{UserData:[]} InstanceId: ResetInvalidOffsets:true} Retry:{Backoff:2s BackoffFunc:<nil>} Fetch:{Min:1 Default:1048576 Max:0} MaxWaitTime:500ms MaxProcessingTime:100ms Return:{Errors:false} Offsets:{CommitInterval:0s AutoCommit:{Enable:true Interval:1s} Initial:-1 Retention:0s Retry:{Max:3}} IsolationLevel:0 Interceptors:[]} ClientID:sarama RackID: ChannelBufferSize:256 ApiVersionsRequest:true Version:2.4.0 MetricRegistry:0xc0009864a0}
panic: kafka: invalid configuration (A SCRAMClientGeneratorFunc function must be provided to Net.SASL.SCRAMClientGeneratorFunc)

goroutine 1 [running]:
flashcat.cloud/categraf/logs/client/kafka.newDestination({{0xc000fcda10, 0x20}, {0xc000d514d0, 0x11}, {0xc000c63340, 0x9}, {0xc000d514d0, 0xc}, 0x44e, 0x0, ...}, ...)
	/home/runner/work/categraf/categraf/logs/client/kafka/destination.go:160 +0xc57
flashcat.cloud/categraf/logs/client/kafka.NewDestination({{0xc000fcda10, 0x20}, {0xc000d514d0, 0x11}, {0xc000c63340, 0x9}, {0xc000d514d0, 0xc}, 0x44e, 0x0, ...}, ...)
	/home/runner/work/categraf/categraf/logs/client/kafka/destination.go:60 +0x8a
flashcat.cloud/categraf/logs/pipeline.NewPipeline(0xc000f1d260, {0x0, 0x0, 0x0}, 0xc000b69c20, 0xc00012b840, {0x5555780?, 0xc000de7e00}, 0x2e?)
	/home/runner/work/categraf/categraf/logs/pipeline/pipeline.go:50 +0x4ea
flashcat.cloud/categraf/logs/pipeline.(*provider).Start(0xc0008a2280)
	/home/runner/work/categraf/categraf/logs/pipeline/provider.go:77 +0x9a
flashcat.cloud/categraf/logs/restart.(*starter).Start(0xc001101c48?)
	/home/runner/work/categraf/categraf/logs/restart/starter.go:30 +0x35
flashcat.cloud/categraf/agent.(*LogsAgent).startInner(0xc0008a2380)
	/home/runner/work/categraf/categraf/agent/logs_agent.go:180 +0x1d7
flashcat.cloud/categraf/agent.(*LogsAgent).Start(0xc0008a2380)
	/home/runner/work/categraf/categraf/agent/logs_agent.go:141 +0x27
flashcat.cloud/categraf/agent.(*Agent).Start(0xc000616978)
	/home/runner/work/categraf/categraf/agent/agent.go:43 +0xef
main.runAgent(0x4c26ac9?)
	/home/runner/work/categraf/categraf/main_posix.go:17 +0x3a
main.main()
	/home/runner/work/categraf/categraf/main.go:113 +0x314
```

### System info

categraf-v0.3.86

### Steps to reproduce

1.调试./categraf --debug --test --inputs logs-agent，出现报错
2.kafka配置无认证时，categraf log.conf配置为PLAIN可以正常
3.
...

### Expected behavior

查看官网支持 SCRAM-SHA-512，但不知道问题在哪里

### Actual behavior

panic: kafka: invalid configuration (A SCRAMClientGeneratorFunc function must be provided to Net.SASL.SCRAMClientGeneratorFunc)

### Additional info

panic: kafka: invalid configuration (A SCRAMClientGeneratorFunc function must be provided to Net.SASL.SCRAMClientGeneratorFunc)

**Comment by kongfei605** [comment]
这个配置开源版本还没放出来，等v0.3.88  放出来

**Comment by kongfei605** [comment]
用这个版本吧 https://github.com/flashcatcloud/categraf/releases/tag/v0.4.1
