### ISSUE TITLE
iptables   input.iptables   panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by QooGeek** [flashcatcloud/categraf#994]
用的 README 默认配置

```
Jul  5 19:10:11 test-nat1 categraf: panic: runtime error: invalid memory address or nil pointer dereference
Jul  5 19:10:11 test-nat1 categraf: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1413841]
Jul  5 19:10:11 test-nat1 categraf: goroutine 98 [running]:
Jul  5 19:10:11 test-nat1 categraf: flashcat.cloud/categraf/inputs/iptables.(*Instance).Gather(0xc000ff6000, 0x4858960?)
Jul  5 19:10:11 test-nat1 categraf: /home/runner/work/categraf/categraf/inputs/iptables/iptables.go:77 +0x121
Jul  5 19:10:11 test-nat1 categraf: flashcat.cloud/categraf/inputs.MayGather(...)
Jul  5 19:10:11 test-nat1 categraf: /home/runner/work/categraf/categraf/inputs/inputs.go:33
Jul  5 19:10:11 test-nat1 categraf: flashcat.cloud/categraf/agent.(*InputReader).gatherOnce.func2({0x5567390, 0xc000ff6000})
Jul  5 19:10:11 test-nat1 categraf: /home/runner/work/categraf/categraf/agent/metrics_reader.go:115 +0x17d
Jul  5 19:10:11 test-nat1 categraf: created by flashcat.cloud/categraf/agent.(*InputReader).gatherOnce in goroutine 15
Jul  5 19:10:11 test-nat1 categraf: /home/runner/work/categraf/categraf/agent/metrics_reader.go:100 +0x370
Jul  5 19:10:12 test-nat1 systemd: categraf.service holdoff time over, scheduling restart.
Jul  5 19:10:12 test-nat1 systemd: Stopped "Categraf".
```

**Comment by tianyanli** [comment]
修复了
![image](https://github.com/flashcatcloud/categraf/assets/38203792/35d2bbc5-9ae5-4c5a-be65-343ff6b6c829)
